server:
  port: 8080

  # https://www.baeldung.com/spring-boot-web-server-shutdown
  shutdown: graceful
spring:
  lifecycle:
    # https://www.baeldung.com/spring-boot-web-server-shutdown
    # timeout config for graceful shutdown
    timeout-per-shutdown-phase: 30s