server:
  port: 8080

  # https://www.baeldung.com/spring-boot-web-server-shutdown
  shutdown: graceful
spring:
  lifecycle:
    # https://www.baeldung.com/spring-boot-web-server-shutdown
    # timeout config for graceful shutdown
    timeout-per-shutdown-phase: 30s
  task:
    execution:
      shutdown:
        # These configure is used for graceful shutdown async process (@Async), and example is AsyncProcessService.java
        await-termination: true
        await-termination-period: 30s
    scheduling:
      shutdown:
        # These configure is used for graceful shutdown cronjob (@Schedule), an example is LongRunCronJob
        await-termination: true
        await-termination-period: 30s